apiVersion: v1
kind: Service
metadata:
  name: rag-backend
  namespace: rag-agent
  labels:
    app: rag-backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: rag-backend
  sessionAffinity: None
