apiVersion: v1
kind: Service
metadata:
  name: rag-frontend
  namespace: rag-agent
  labels:
    app: rag-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: rag-frontend
  sessionAffinity: None
