apiVersion: v1
kind: Service
metadata:
  name: rag-minio
  namespace: rag-agent
  labels:
    app: rag-minio
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 9000
    targetPort: api
    protocol: TCP
  - name: console
    port: 9001
    targetPort: console
    protocol: TCP
  selector:
    app: rag-minio
  sessionAffinity: None
